eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 
  instance:
    hostname: localhost

microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder  
